### ISSUE TITLE
Running With the Go Tool

### ISSUE THREAD

**Issue by rauljordan** [prysmaticlabs/go-bls#22]
Hi all,

Although we primarily aim to support this project as a pure Bazel project, some users may want to try out the Go tool for various reasons or IDE support. However, a naive go build or go test will currently fail, as it cannot find `include/mcl/bls.h`. Even checking in https://github.com/prysmaticlabs/mcl will still cause:
```
$ go build .
# github.com/prysmaticlabs/go-bls
./bls.go:6:29: fatal error: include/mcl/bls.h: No such file or directory
compilation terminated.
```
Additionally, users will need to make the libraries in MCL and add them to their LD_LIBRARY_PATH (if on a Linux machine) in order for the system to work. Opening this issue for discussion on improving this.

**Comment by rauljordan** [comment]
@robin-thomas do you have suggestions on getting over the include/mcl/bls.h issue mentioned above? Thank you.

**Comment by prestonvanloon** [comment]
There is no way to do this without some additional build tooling. Some makefile or bazel system will be required to build this library. At a minimum, you would need to `make` to bootstrap the libraries. 

You _should_ be able to use any existing go tool with a bazel built binary.

**Comment by robin-thomas** [comment]
@rauljordan, I have to go with what @prestonvanloon said too. You might need an additional build tool.

`Even checking in https://github.com/prysmaticlabs/mcl will still cause`. It's all about relative paths. So where did you checked in the repo (with respect to the go-bls repo)?

**Comment by rauljordan** [comment]
Agreed no way to do this, closing for this project
