### ISSUE TITLE
Running go-bls tests for the first time results in error

### ISSUE THREAD

**Issue by robin-thomas** [prysmaticlabs/go-bls#7]
Running go-bls for the first time with the instructions mentioned in the README.md fails with the below error message.

```
$ bazel test //...
INFO: Invocation ID: 0414e820-4aff-43e5-b81c-112516ad7e8b
INFO: Analysed 3 targets (0 packages loaded, 0 targets configured).
INFO: Found 2 targets and 1 test target...
ERROR: missing input file '//:mcl/lib/libbls384_dy.so'
ERROR: /home/<user>/go-bls/BUILD.bazel:28:1: //:mcl-compiled-lib: missing input file '//:mcl/lib/libbls384_dy.so'
ERROR: /home/<user>/go-bls/BUILD.bazel:28:1 1 input file(s) do not exist
INFO: Elapsed time: 0.152s, Critical Path: 0.00s
INFO: 0 processes.
FAILED: Build did NOT complete successfully
//:go_default_test                                                    NO STATUS

FAILED: Build did NOT complete successfully
```

### OS
> Ubuntu 16.04

### Bazel version
> 0.20.0

### Any additional info
> libgmp is not installed

**Comment by rauljordan** [comment]
Hey @robin-thomas the problem with this library is it requires a few static objects generated by Make to be in your LD_LIBRARY_PATH. This sucks because the only option seems for us to check them into the repo AND require the user to set the LD_LIBRARY_PATH env variable to the folder where the libraries are in the repo. Given you are more familiar with file systems, what do you think a good alternative to this would be?

The repo uses cgo to interact with the lower level, C cryptography library called MCL. Cgo expects the LD_LIBRARY_PATH env var to be set on your system in order to run the project, which is unrealistic to expect from users. Unfortunately, this seems to be more of an issue with the design of the underlying MCL library by its author, Herumi.

**Comment by robin-thomas** [comment]
@rauljordan Let me make sure I understood correctly.

To run the tests, it requires *go_default_library*, which is dependent on *mcl-compiled-lib*. To build this library, you require *libbls384.a* and *libbls384_dy.so*. Looking at https://github.com/prysmaticlabs/mcl/tree/master/lib, I can see these libraries seem to be present already and imported with *git_repository* (even though they may not work since it might not have been built for my architecture. But at the very least, the libraries should be found).

But even though you have the *git-repository* (which is depreciated; need to use correct one), it is not downloaded, because nothing depends on it. So if I modify your BUILD.bazel file to like shown below,
```go_library(
    name = "go_default_library",
    srcs = [
        "bls.go",
        "crypto.go",
        "mcl/include/mcl/bls.h",    <-- I want to change this too. But need to change visibility
        "mcl/include/mcl/bn.h",
        "mcl/include/mcl/curve_type.h",
    ],
    cdeps = [
        "@herumi_mcl//:mcl-lib",
    ],
    cgo = True,
    clinkopts = ["-lstdc++"],
    copts = ["-DMCLBN_FP_UNIT_SIZE=6 -DMCL_DONT_USE_OPENSSL"],
    importpath = "github.com/prysmaticlabs/go-bls",
    visibility = ["//visibility:public"],
)
```

It now finds the libraries and compiles! But it throws missing symbols mostly about GMP. Now that's something we can fix :)

But we need hierachical WORKSPACE support for that to work cleanly: https://github.com/bazelbuild/bazel/issues/1943

**Comment by robin-thomas** [comment]
I want to be able to include the header files from https://github.com/prysmaticlabs/mcl

To do that, add this to the top of BUILD file in https://github.com/prysmaticlabs/mcl
```
exports_files([
    "include/mcl/bls.h",
    "include/mcl/bn.h",
    "include/mcl/curve_type.h",
])
```

Update to `#include "external/herumi_mcl/include/mcl/bls.h"` in the `crypto.go` and `bls.go`.

This approach of copying the entire `mcl` directory to `go-bls` workspace is not good. If you try my approach, then you can update your fork of `herumi_mcl` when required (or even directly point to the original repo, and use Bazel as a wrapper to build the libraries) without polluting `go-bls`. That way, when the repo gets updated, its much easier to manage the dependency with Bazel. `go-bls` repo looks much cleaner too.

Then I can update the BUILD in `go-bls` to:
```name = "go_default_library",
    srcs = [
        "bls.go",
        "crypto.go",
        "@herumi_mcl//:include/mcl/bls.h",
        "@herumi_mcl//:include/mcl/bn.h",
        "@herumi_mcl//:include/mcl/curve_type.h",
    ],
    cdeps = [
        "@herumi_mcl//:mcl-lib",
    ],
    cgo = True,
    clinkopts = ["-lstdc++"],
    copts = ["-DMCLBN_FP_UNIT_SIZE=6 -DMCL_DONT_USE_OPENSSL"],
    importpath = "github.com/prysmaticlabs/go-bls",
    visibility = ["//visibility:public"],
)
```

No more need for the `mcl` directory in `go-bls`.

**Comment by robin-thomas** [comment]
@rauljordan I have two more errors to fix in this: GMP looks fine for now.

```
bazel-out/k8-fastbuild/bin/_solib_k8/_U@herumi_Umcl_S_S_Cmcl-lib___Uexternal_Sherumi_Umcl_Slib/libbls384_dy.so: error: undefined reference to 'SHA256'
bazel-out/k8-fastbuild/bin/_solib_k8/_U@herumi_Umcl_S_S_Cmcl-lib___Uexternal_Sherumi_Umcl_Slib/libbls384_dy.so: error: undefined reference to 'SHA512'
```
where are these symbols supposed to be in? (I used the libraries stored in `mcl` repo)

**Comment by rauljordan** [comment]
Hey @robin-thomas this is awesome, thank you for the work on this. With respect to not using Herumi's MCL library checked into the repo, the reason for this is because his project structure is quite complex.

He has 2 projects, https://github.com/herumi/mcl and https://github.com/herumi/bls. They are basically the same repo but bls is a stripped down MCL. What I did in this case was just add all the files in bls into mcl, modified the make files, and basically merged Herumi's two projects into one. The cgo bindings depend on some libs generated by Make as you've noticed from your work on this. These are architecture dependent and contain references to linked libraries at compile time of whomever generated them.

In particular, I generated these libs with GMP and OpenSSL. Herumi has the ability to make both of these optional, but it seems you do not have openssl installed, which I did when making the libraries. This is what's causing the undefined ref. I think Herumi allows for us to make openssl optional when making the libraries, so doing that should fix the issue.

**Comment by rauljordan** [comment]
Would you be able to submit a pull request with your changes? Would love to have a simplified structure and bazel building the project :)

**Comment by robin-thomas** [comment]
@rauljordan Definitely. But do I have push permission for the repo?

**Comment by robin-thomas** [comment]
Its in `libcrypto`, which is not linked, because I don't see the mention anywhere in Bazel build file in prysmaticlabs's mcl repo. Might be a headache getting it integrated into Bazel. BoringSSL would be better choice, I guess.

Anyway, I have added `-lcrypto` for now. That will work fine in Linux anyway. And I run all the tests in `go-bls`. It works fine now. No need to install GMP :)

```
$ bazel test ...
Starting local Bazel server and connecting to it...
INFO: Invocation ID: 99eda854-a7d8-4b32-8783-0555d680f83f
INFO: SHA256 (https://codeload.github.com/golang/tools/zip/3e7aa9e59977626dc60433e9aeadf1bb63d28295) = 2384fa91351a7414b643c5230422ce45f5aa2be8a82727609afd4e64e6973a30
INFO: Repository rule 'bazelify_gmp' returned: {"remote": "https://github.com/robin-thomas/bazelify-gmp", "commit": "3819642a7f67cb6cd001edb862079238eb6d0a18", "shallow_since": "2018-12-23", "init_submodules": False, "verbose": False, "strip_prefix": "", "patches": [], "patch_tool": "patch", "patch_args": ["-p0"], "patch_cmds": [], "name": "bazelify_gmp"}
INFO: Analysed 3 targets (33 packages loaded, 8822 targets configured).
INFO: Found 2 targets and 1 test target...
INFO: Elapsed time: 47.023s, Critical Path: 36.17s
INFO: 378 processes: 378 linux-sandbox.
INFO: Build completed successfully, 411 total actions
//:go_default_test                                                       PASSED in 0.1s

Executed 1 out of 1 test: 1 test passes.
INFO: Build completed successfully, 411 total actions
```

**Comment by rauljordan** [comment]
Hi @robin-thomas Im on the latest master after making the libraries locally and updated the commit hash of mcl to the latest master of mcl in go-bls, and getting:

```
$ bazel test //...
INFO: Analysed 4 targets (0 packages loaded).
INFO: Found 3 targets and 1 test target...
ERROR: /home/zypherx/.cache/bazel/_bazel_zypherx/6dc90437243ef5aea30a94d0f60323cd/external/herumi_mcl/BUILD.bazel:7:1: C++ compilation of rule '@herumi_mcl//:mcl-lib' failed (Exit 1)
In file included from external/herumi_mcl/include/mcl/op.hpp:9:0,
                 from external/herumi_mcl/include/mcl/fp.hpp:29,
                 from external/herumi_mcl/include/mcl/fp_tower.hpp:9,
                 from external/herumi_mcl/include/mcl/bn.hpp:9,
                 from external/herumi_mcl/include/mcl/bn384.hpp:10,
                 from external/herumi_mcl/src/bn_c_impl.hpp:7,
                 from external/herumi_mcl/src/bls_c_impl.hpp:6,
                 from external/herumi_mcl/src/bls_c384.cpp:2:
external/herumi_mcl/include/mcl/gmp_util.hpp:31:19: fatal error: gmpxx.h: No such file or directory
compilation terminated.
INFO: Elapsed time: 1.178s, Critical Path: 1.00s
INFO: 19 processes: 19 linux-sandbox.
FAILED: Build did NOT complete successfully
//:go_default_test                                                    NO STATUS

FAILED: Build did NOT complete successfully
```
I tried a few things:
- Making the libraries with `make MCL_USE_GMP=0` without gmp installed on my machine
- Making the libraries with `make MCL_USE_GMP=1` with gmp installed

The second one requires the user to have gmp installed. Any idea as to what may be happening? I'm on ubuntu 16.04.

Also, the second option led to the following error in cgo:
```
$ bazel test //...
INFO: Analysed 4 targets (0 packages loaded).
INFO: Found 3 targets and 1 test target...
ERROR: /home/user/Desktop/Go/src/github.com/prysmaticlabs/go-bls/BUILD.bazel:3:1: CGoCodeGen //:go_default_library%linux_amd64%cgo_codegen failed (Exit 1)
/tmp/srcdir186888981/bls.go:6:49: fatal error: external/herumi_mcl/include/mcl/bls.h: No such file or directory
compilation terminated.
CgoCodegen: error running subcommand: exit status 2
INFO: Elapsed time: 7.013s, Critical Path: 0.18s
INFO: 319 processes: 319 linux-sandbox.
FAILED: Build did NOT complete successfully
//:go_default_test                                                    NO STATUS

FAILED: Build did NOT complete successfully
```

**Comment by robin-thomas** [comment]
@rauljordan 
gmpxx.h is part of cxx library of gmp. Pretty weird, since I'm on Ubuntu 16.04 too and had set it to use c library of GMP.

Can you make another branch on go-bls, and push to it? I'll take a look.

**Comment by rauljordan** [comment]
Sure thing @robin-thomas, pushed to https://github.com/prysmaticlabs/go-bls/tree/gmpxx.

I cleaned and expunged the Bazel cache, made the MCL libraries with MCL_USE_GMP=0 and got the gmpxx error on Ubuntu.

```
$ bazel build //...
INFO: Analysed 4 targets (34 packages loaded).
INFO: Found 4 targets...
ERROR: /home/zypherx/.cache/bazel/_bazel_zypherx/6dc90437243ef5aea30a94d0f60323cd/external/herumi_mcl/BUILD.bazel:7:1: C++ compilation of rule '@herumi_mcl//:mcl-lib' failed (Exit 1)
In file included from external/herumi_mcl/include/mcl/op.hpp:9:0,
                 from external/herumi_mcl/include/mcl/fp.hpp:29,
                 from external/herumi_mcl/include/mcl/fp_tower.hpp:9,
                 from external/herumi_mcl/include/mcl/bn.hpp:9,
                 from external/herumi_mcl/include/mcl/bn384.hpp:10,
                 from external/herumi_mcl/src/bn_c_impl.hpp:7,
                 from external/herumi_mcl/src/bls_c_impl.hpp:6,
                 from external/herumi_mcl/src/bls_c384.cpp:2:
external/herumi_mcl/include/mcl/gmp_util.hpp:31:19: fatal error: gmpxx.h: No such file or directory
compilation terminated.
INFO: Elapsed time: 3.843s, Critical Path: 1.50s
INFO: 40 processes: 40 linux-sandbox.
FAILED: Build did NOT complete successfully
```

**Comment by rauljordan** [comment]
I uninstalled gmp from my machine beforehand as well

**Comment by robin-thomas** [comment]
@rauljordan 
Replace the BUILD file `go_library` like shown below.

```
go_library(
    name = "go_default_library",
    srcs = [
        "bls.go",
        "crypto.go",
    ],
    cdeps = [
        "go-lib",
    ],
    cgo = True,
    clinkopts = ["-lstdc++"],
    copts = ["-DMCLBN_FP_UNIT_SIZE=6 -DMCL_DONT_USE_OPENSSL"],
    importpath = "github.com/prysmaticlabs/go-bls",
    visibility = ["//visibility:public"],
)
```

**Comment by rauljordan** [comment]
Hi @robin-thomas just pushed that to the gmpxx branch and now we get
```
$ bazel build //...
INFO: Analysed 4 targets (1 packages loaded).
INFO: Found 4 targets...
ERROR: /home/zypherx/.cache/bazel/_bazel_zypherx/6dc90437243ef5aea30a94d0f60323cd/external/herumi_mcl/BUILD.bazel:7:1: C++ compilation of rule '@herumi_mcl//:mcl-lib' failed (Exit 1)
In file included from external/herumi_mcl/include/mcl/op.hpp:9:0,
                 from external/herumi_mcl/src/fp.cpp:1:
external/herumi_mcl/include/mcl/gmp_util.hpp:31:19: fatal error: gmpxx.h: No such file or directory
compilation terminated.
INFO: Elapsed time: 3.475s, Critical Path: 1.36s
INFO: 68 processes: 68 linux-sandbox.
FAILED: Build did NOT complete successfully
```

**Comment by robin-thomas** [comment]
@rauljordan That's just weird. Coz I'm getting the below output.

```
$ bazel build //...
Starting local Bazel server and connecting to it...
INFO: Invocation ID: 2e90ce15-e1fb-4be9-8eab-c8f7daa06861
INFO: SHA256 (https://codeload.github.com/golang/tools/zip/3e7aa9e59977626dc60433e9aeadf1bb63d28295) = 2384fa91351a7414b643c5230422ce45f5aa2be8a82727609afd4e64e6973a30
INFO: Repository rule 'bazelify_gmp' returned: {"remote": "https://github.com/robin-thomas/bazelify-gmp", "commit": "3819642a7f67cb6cd001edb862079238eb6d0a18", "shallow_since": "2018-12-23", "init_submodules": False, "verbose": False, "strip_prefix": "", "patches": [], "patch_tool": "patch", "patch_args": ["-p0"], "patch_cmds": [], "name": "bazelify_gmp"}
INFO: Repository rule 'herumi_mcl' returned: {"remote": "https://github.com/prysmaticlabs/mcl", "commit": "9355e1d3cef12321fb1002f5707a3655bed7c361", "shallow_since": "2018-12-23", "init_submodules": False, "verbose": False, "strip_prefix": "", "patches": [], "patch_tool": "patch", "patch_args": ["-p0"], "patch_cmds": [], "name": "herumi_mcl"}
INFO: Repository rule 'boringssl' returned: {"remote": "https://github.com/google/boringssl", "commit": "fafc4482e85c09e7af5f71b2eb287b73ccd1020a", "shallow_since": "2018-12-21", "init_submodules": False, "verbose": False, "strip_prefix": "", "patches": [], "patch_tool": "patch", "patch_args": ["-p0"], "patch_cmds": [], "name": "boringssl"}
INFO: Analysed 4 targets (34 packages loaded, 9254 targets configured).
INFO: Found 4 targets...
INFO: Elapsed time: 76.135s, Critical Path: 41.25s
INFO: 622 processes: 622 linux-sandbox.
INFO: Build completed successfully, 657 total actions
```

Can you run the command `bazel clean --expunge` and then try building again?

**Comment by rauljordan** [comment]
This is on the gmpxx branch? do you have gmp installed globally on your machine as well? I did `sudo apt-get remove libgmp-dev` before building the libraries with make. Did an expunge and still receive the error...will investigate more.

**Comment by robin-thomas** [comment]
Ah, seems like I had gmp installed in my system. So even though it used the gmp library I had built with Bazel, the headers (gmpxx.h) were loaded from global. Let me fix my repo to export this file and see.

**Comment by robin-thomas** [comment]
@rauljordan I have made 2 PRs to fix this issue: https://github.com/prysmaticlabs/mcl/pull/2. 
https://github.com/prysmaticlabs/go-bls/pull/10

After merging, in the `gmpxx` branch on `go-bls`, update the `mcl` repo commit to the latest one in the `git_repository`. Run `bazel clean --expunge` in `go-bls` and try running the bazel tests again. Should work now.

**Comment by robin-thomas** [comment]
Fixed by https://github.com/prysmaticlabs/go-bls/issues/9
